#!/bin/sh

ori=$(hyprctl monitors | grep -m 1 transform | awk '{print $2}')

if [ -v HYPR_4K ]; then
  if [ $ori -eq 0 ]; then
      hyprctl --batch 'keyword monitor ,highrr,auto,2,transform,1 ; dispatch layoutmsg orientationbottom'
  else
      hyprctl --batch 'keyword monitor ,highrr,auto,2,transform,0 ; dispatch layoutmsg orientationleft'
  fi
else
  if [ $ori -eq 0 ]; then
      hyprctl --batch 'keyword monitor ,highrr,auto,auto,transform,1 ; dispatch layoutmsg orientationbottom'
  else
      hyprctl --batch 'keyword monitor ,highrr,auto,auto,transform,0 ; dispatch layoutmsg orientationleft'
  fi
fi
