#!/bin/bash
if [[ $(ip link | grep -c "state UP") -ne 0 ]]; then
    nname=$(ip link | grep "state UP" | sed "s/.*: \(.*\): .*/\1/")
    i6addr=$(ip addr show $nname \
        | grep -E "inet6 .* global" \
        | awk '{print $2}')
    i4addr=$(ip addr show $nname \
        | grep -E "inet .* global" \
        | awk '{print $2}')
else
    nname=disconnected
fi
if [ -n $1 ] && [ "ipv6" == "$1" ]; then
    echo $i6addr
elif [ "ipv4" == "$1" ]; then
    echo $i4addr
elif [ "device" == "$1" ]; then
    echo $nname
else
    echo -e "${nname}\n${i4addr}\n${i6addr}"
fi
